// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WidgetType = "favorites" | "recent" | "projects" | "watched_folders" | "item" | "clock" | "stats" | "quick_note" | "exe_folder" | "daily_task" | "snippet" | "clipboard_history" | "file_search" | "system_monitor";
